// ignore_for_file: constant_identifier_names

class UserAccessMenu {
  static const String POS_ACCESS = "POS_ACCESS";
  static const String PAYMENT_SETUP = "PAYMENT_SETUP";
  static const String PRINTER_SETUP = "PRINTER_SETUP";
  static const String BLUETOOTH_SETUP = "BLUETOOTH_SETUP";
  static const String MULTI_POS_SETUP = "MULTI_POS_SETUP";
  static const String SECURITY_SETTINGS = "SECURITY_SETTINGS";
  static const String MODE_SETTINGS = "MODE_SETTINGS";
  static const String MANAGE_TABLE_SETTINGS = "MANAGE_TABLE_SETTINGS";
  static const String REPRINT_TRANSACTION = "REPRINT_TRANSACTION";
  static const String SETTLEMENT_SETUP = "SETTLEMENT_SETUP";
  static const String DISABLE_STORE_ITEM_VARIANT = "DISABLE_STORE_ITEM_VARIANT";
  static const String APPLY_VARIABLE_PRICE = "APPLY_VARIABLE_PRICE";
  static const String INPUT_ITEM_INVENTORY = "INPUT_ITEM_INVENTORY";
  static const String INPUT_ADD_ON_INVENTORY = "INPUT_ADD_ON_INVENTORY";
  static const String INPUT_COMPONENT_INVENTORY = "INPUT_COMPONENT_INVENTORY";
  static const String UPDATE_ITEM_INVENTORY = "UPDATE_ITEM_INVENTORY";
  static const String UPDATE_ADD_ON_INVENTORY = "UPDATE_ADD_ON_INVENTORY";
  static const String UPDATE_COMPONENT_INVENTORY = "UPDATE_COMPONENT_INVENTORY";
  static const String PROCESS_COMPONENT_INVENTORY = "PROCESS_COMPONENT_INVENTORY";
  static const String MANAGE_CASH = "MANAGE_CASH";
  static const String MANAGE_ACCOUNT = "MANAGE_ACCOUNT";
  static const String SEE_ACCOUNT_BALANCE = "SEE_ACCOUNT_BALANCE";
  static const String APPLY_DISCOUNT = "APPLY_DISCOUNT";
  static const String APPLY_PROMOTION = "APPLY_PROMOTION";
  static const String APPLY_SURCHARGE = "APPLY_SURCHARGE";
  static const String APPLY_TAX = "APPLY_TAX";
  static const String APPLY_VOUCHER = "APPLY_VOUCHER";
  static const String CUSTOM_ADJUSTMENTS = "CUSTOM_ADJUSTMENTS";
  static const String VOID_TRANSACTIONS = "VOID_TRANSACTIONS";
  static const String REFUND_TRANSACTIONS = "REFUND_TRANSACTIONS";
  static const String MODIFY_PENDING_TRANSACTIONS = "MODIFY_PENDING_TRANSACTIONS";
  static const String SAVE_TRANSACTIONS = "SAVE_TRANSACTIONS";
  static const String CANCEL_TRANSACTIONS = "CANCEL_TRANSACTIONS";
  static const String APPLY_COMMISSION = "APPLY_COMMISSION";
  static const String CREATE_PURCHASE_ORDER = "CREATE_PURCHASE_ORDER";
  static const String UPDATE_PURCHASE_ORDER = "UPDATE_PURCHASE_ORDER";
  static const String CANCEL_PURCHASE_ORDER = "CANCEL_PURCHASE_ORDER";
  static const String CONFIRM_PURCHASE_ORDER = "CONFIRM_PURCHASE_ORDER";
  static const String RECEIVE_PURCHASE_ORDER = "RECEIVE_PURCHASE_ORDER";
  static const String UPDATE_PURCHASE_ORDER_PRICE = "UPDATE_PURCHASE_ORDER_PRICE";
  static const String PAY_PURCHASE_ORDER = "PAY_PURCHASE_ORDER";
  static const String INSTANT_PURCHASE_ORDER = "INSTANT_PURCHASE_ORDER";
  static const String CREATE_TRANSFER_ORDER = "CREATE_TRANSFER_ORDER";
  static const String UPDATE_TRANSFER_ORDER = "UPDATE_TRANSFER_ORDER";
  static const String CANCEL_TRANSFER_ORDER = "CANCEL_TRANSFER_ORDER";
  static const String CONFIRM_TRANSFER_ORDER = "CONFIRM_TRANSFER_ORDER";
  static const String SEND_TRANSFER_ORDER = "SEND_TRANSFER_ORDER";
  static const String RECEIVE_TRANSFER_ORDER = "RECEIVE_TRANSFER_ORDER";
  static const String PAY_TRANSFER_ORDER = "PAY_TRANSFER_ORDER";
  static const String INSTANT_TRANSFER_ORDER = "INSTANT_TRANSFER_ORDER";
  static const String MANAGE_ASSET = "MANAGE_ASSET";
  static const String MANAGE_COA = "MANAGE_COA";
  static const String POST_JOURNAL = "POST_JOURNAL";
  static const String RECONCILE = "RECONCILE";
  static const String BALANCE_SHEET = "BALANCE_SHEET";
  static const String INCOME_STATEMENT = "INCOME_STATEMENT";
  static const String CASH_FLOW_STATEMENT = "CASH_FLOW_STATEMENT";
  static const String COA_REPORT = "COA_REPORT";
  static const String JOURNAL_REPORT = "JOURNAL_REPORT";

  static const String SALES_REPORT = "SALES_REPORT";
  static const String REFUND_VOID_REPORT = "REFUND_VOID_REPORT";
  static const String SALES_DAILY_HOURLY_REPORT = "SALES_DAILY_HOURLY_REPORT";
  static const String PROFIT_COST_REPORT = "PROFIT_COST_REPORT";
  static const String TRANSACTION_REPORT = "TRANSACTION_REPORT";
  static const String CASH_FLOW_REPORT = "CASH_FLOW_REPORT";
  static const String BANK_ACCOUNT_REPORT = "BANK_ACCOUNT_REPORT";
  static const String POPULAR_TRENDING_ITEM_REPORT = "POPULAR_TRENDING_ITEM_REPORT";
  static const String CORRELATION_ITEM_REPORT = "CORRELATION_ITEM_REPORT";
  static const String SUPPLIER_REPORT = "SUPPLIER_REPORT";
  static const String PURCHASE_ORDER_REPORT = "PURCHASE_ORDER_REPORT";
  static const String ITEM_SALES_REPORT = "ITEM_SALES_REPORT";
  static const String ITEM_INVENTORY_REPORT = "ITEM_INVENTORY_REPORT";
  static const String ADD_ON_INVENTORY_REPORT = "ADD_ON_INVENTORY_REPORT";
  static const String COMPONENT_INVENTORY_REPORT = "COMPONENT_INVENTORY_REPORT";
  static const String COMPONENT_PRODUCTION_REPORT = "COMPONENT_PRODUCTION_REPORT";
  static const String WASTE_REPORT = "WASTE_REPORT";
  static const String ITEM_PROCESSING_REPORT = "ITEM_PROCESSING_REPORT";
  static const String CUSTOMER_REPORT = "CUSTOMER_REPORT";
  static const String EMPLOYEE_SALES_REPORT = "EMPLOYEE_SALES_REPORT";
  static const String EMPLOYEE_SALARY_REPORT = "EMPLOYEE_SALARY_REPORT";
  static const String EMPLOYEE_SHIFT_REPORT = "EMPLOYEE_SHIFT_REPORT";
  static const String DISCOUNT_PROMO_REPORT = "DISCOUNT_PROMO_REPORT";
  static const String AGENT_REPORT = "AGENT_REPORT";
  static const String VOUCHER_REPORT = "VOUCHER_REPORT";

  static List<String> getAllUserAccessMenu() {
    List<String> accesses = [];
    accesses.add(POS_ACCESS);
    accesses.add(PAYMENT_SETUP);
    accesses.add(PRINTER_SETUP);
    accesses.add(BLUETOOTH_SETUP);
    accesses.add(MULTI_POS_SETUP);
    accesses.add(SECURITY_SETTINGS);
    accesses.add(MODE_SETTINGS);
    accesses.add(MANAGE_TABLE_SETTINGS);
    accesses.add(REPRINT_TRANSACTION);
    accesses.add(SETTLEMENT_SETUP);
    accesses.add(DISABLE_STORE_ITEM_VARIANT);
    accesses.add(APPLY_VARIABLE_PRICE);
    accesses.add(INPUT_ITEM_INVENTORY);
    accesses.add(INPUT_ADD_ON_INVENTORY);
    accesses.add(INPUT_COMPONENT_INVENTORY);
    accesses.add(UPDATE_ITEM_INVENTORY);
    accesses.add(UPDATE_ADD_ON_INVENTORY);
    accesses.add(UPDATE_COMPONENT_INVENTORY);
    accesses.add(PROCESS_COMPONENT_INVENTORY);
    accesses.add(MANAGE_CASH);
    accesses.add(MANAGE_ACCOUNT);
    accesses.add(SEE_ACCOUNT_BALANCE);
    accesses.add(APPLY_DISCOUNT);
    accesses.add(APPLY_PROMOTION);
    accesses.add(APPLY_SURCHARGE);
    accesses.add(APPLY_TAX);
    accesses.add(APPLY_VOUCHER);
    accesses.add(CUSTOM_ADJUSTMENTS);
    accesses.add(VOID_TRANSACTIONS);
    accesses.add(REFUND_TRANSACTIONS);
    accesses.add(MODIFY_PENDING_TRANSACTIONS);
    accesses.add(CANCEL_TRANSACTIONS);
    accesses.add(APPLY_COMMISSION);
    accesses.add(CREATE_PURCHASE_ORDER);
    accesses.add(UPDATE_PURCHASE_ORDER);
    accesses.add(CANCEL_PURCHASE_ORDER);
    accesses.add(CONFIRM_PURCHASE_ORDER);
    accesses.add(RECEIVE_PURCHASE_ORDER);
    accesses.add(UPDATE_PURCHASE_ORDER_PRICE);
    accesses.add(PAY_PURCHASE_ORDER);
    accesses.add(INSTANT_PURCHASE_ORDER);
    accesses.add(CREATE_TRANSFER_ORDER);
    accesses.add(UPDATE_TRANSFER_ORDER);
    accesses.add(CANCEL_TRANSFER_ORDER);
    accesses.add(CONFIRM_TRANSFER_ORDER);
    accesses.add(SEND_TRANSFER_ORDER);
    accesses.add(RECEIVE_TRANSFER_ORDER);
    accesses.add(PAY_TRANSFER_ORDER);
    accesses.add(INSTANT_TRANSFER_ORDER);
    accesses.add(MANAGE_ASSET);
    accesses.add(MANAGE_COA);
    accesses.add(POST_JOURNAL);
    accesses.add(RECONCILE);
    accesses.add(BALANCE_SHEET);
    accesses.add(INCOME_STATEMENT);
    accesses.add(CASH_FLOW_STATEMENT);
    accesses.add(COA_REPORT);
    accesses.add(JOURNAL_REPORT);
    accesses.add(SALES_REPORT);
    accesses.add(REFUND_VOID_REPORT);
    accesses.add(SALES_DAILY_HOURLY_REPORT);
    accesses.add(PROFIT_COST_REPORT);
    accesses.add(TRANSACTION_REPORT);
    accesses.add(CASH_FLOW_REPORT);
    accesses.add(BANK_ACCOUNT_REPORT);
    accesses.add(POPULAR_TRENDING_ITEM_REPORT);
    accesses.add(CORRELATION_ITEM_REPORT);
    accesses.add(SUPPLIER_REPORT);
    accesses.add(PURCHASE_ORDER_REPORT);
    accesses.add(ITEM_SALES_REPORT);
    accesses.add(ITEM_INVENTORY_REPORT);
    accesses.add(ADD_ON_INVENTORY_REPORT);
    accesses.add(COMPONENT_INVENTORY_REPORT);
    accesses.add(COMPONENT_PRODUCTION_REPORT);
    accesses.add(WASTE_REPORT);
    accesses.add(ITEM_PROCESSING_REPORT);
    accesses.add(CUSTOMER_REPORT);
    accesses.add(EMPLOYEE_SALES_REPORT);
    accesses.add(EMPLOYEE_SALARY_REPORT);
    accesses.add(EMPLOYEE_SHIFT_REPORT);
    accesses.add(DISCOUNT_PROMO_REPORT);
    accesses.add(AGENT_REPORT);
    accesses.add(VOUCHER_REPORT);
    return accesses;
  }
}
